# Generated by Django 4.2.2 on 2023-07-04 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cuentas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personaje', models.CharField(max_length=40)),
                ('tecnica', models.CharField(max_length=40)),
            ],
        ),
    ]
